# Generated by Django 4.2.2 on 2023-06-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('additional_people', models.IntegerField()),
                ('allergies', models.CharField(max_length=1000)),
                ('alcohol', models.CharField(max_length=1000)),
                ('other', models.CharField(max_length=5000)),
            ],
        ),
    ]
