# Generated by Django 4.2.2 on 2023-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0003_alter_registryentry_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryentry',
            name='reserved_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
