# Generated by Django 4.2.2 on 2023-07-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0011_alter_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='default/default.png', upload_to='profile_pics'),
        ),
    ]
