# Generated by Django 4.2.2 on 2023-07-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0012_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default/default.png', upload_to='profile_pics'),
        ),
    ]
