# Generated by Django 4.2.2 on 2023-08-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0013_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='additional_people',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='alcohol',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='allergies',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='other',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
