# Generated by Django 4.2.2 on 2023-08-01 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0015_remove_rsvp_full_name_rsvp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rsvp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='WeddingWebsite.rsvp'),
        ),
    ]
