# Generated by Django 4.2.2 on 2023-08-05 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0019_alter_thread_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryentry',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
