# Generated by Django 4.2.2 on 2023-08-17 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0020_alter_registryentry_reserved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.CreateModel(
            name='PostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeddingWebsite.post')),
            ],
        ),
    ]
