# Generated by Django 4.2.2 on 2023-08-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0021_remove_post_creation_time_remove_post_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postversion',
            options={'ordering': ('creation_time',)},
        ),
    ]
