# Generated by Django 4.2.2 on 2023-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0024_alter_postversion_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='other',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
