# Generated by Django 4.2.2 on 2023-12-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0026_alter_post_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='additional_people',
            new_name='party_size',
        ),
    ]
