# Generated by Django 4.2.2 on 2023-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingWebsite', '0027_rename_additional_people_rsvp_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
